config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flights#index"

  resources :flights
  resources :reservations

  get 'reservations(/:id)/change', to: 'reservations#change', as: :change
  get 'reservations(/:id)/payment', to: 'reservations#payment', as: :payment
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/airline.rb
class Airline < ApplicationRecord
	has_many :flights

	validates :title, presence: true
	validates :fs_code, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :airline
  has_and_belongs_to_many :reservations

  validates :origin, presence: true
  validates :destination, presence: true
  validates :departure_time, presence: true
  validates :arrival_time, presence: true
  validates :airline, presence: true
  validates :price, presence: true
end

app/models/flights_reservation.rb
class FlightsReservation < ApplicationRecord
  belongs_to :reservation
  belongs_to :flight
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :reservation
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :flights
  has_one :payment

  validates :name, presence: true
  before_save :calculate_price

  private
  def calculate_price
      self.value = self.flights.select(:price).sum{|flight| flight[:price] } if self.flights
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reservations

  validates :name, presence: true
  after_create :set_default_reservation

  private
  def set_default_reservation
    self.reservations.create(name: "Mi Primer Viaje con Jaffly")
    self.defaultReservation = self.reservations.first.id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email])
	end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	def index
		@flights = Flight.where('arrival_time > ?', Time.now.next_day.to_i )
	end

	def edit
		set_flight_item

		respond_to do |format|
			@flight_item.reservations << Reservation.find(current_user.defaultReservation)
			if Reservation.find(current_user.defaultReservation).save
				format.html { redirect_to flights_path, notice: 'Your flight has been added to your Reservation' }
			else
				format.html { render :new }
			end
		end
	end

	private

	def flight_params
		flight_params = params.require(:flight).permit(:id)
	end

	def set_flight_item
		@flight_item = Flight.find(params[:id])
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_action :set_reservation_item, only: [:edit, :update, :show, :destroy]

	def index
		@reservations = Reservation.where(user_id: current_user.id)
	end

	def new
		@reservation_item = Reservation.new
	end

	def create
		@reservation_item = Reservation.new(reservation_params)

		respond_to do |format|
			@reservation_item.user_id = current_user.id
			if @reservation_item.save
				format.html { redirect_to reservations_path, notice: 'Your reservation item is now live' }
			else
				format.html { render :new }
			end
		end
	end

	def show
		set_reservation_item
	end

	def edit
		set_reservation_item
	end

	def update
		set_reservation_item

		respond_to do |format|
			if @reservation_item.update(reservation_params)
				format.html { redirect_to reservations_path, notice: 'Reservation was successfully updated.' }
			else
				format.html { render :edit }
			end
		end
	end

	def destroy
		set_reservation_item
		@reservation_item.destroy

		respond_to do |format|
			format.html { redirect_to reservations_path, notice: 'Record was removed' }
		end
	end

	def change
		set_reservation_item
		if @reservation_item
			User.find(current_user.id).update(defaultReservation: set_reservation_item.id)
			respond_to do |format|
				format.html { redirect_to flights_path, notice: 'Current Reservation has been changed.' }
			end
		end
	end

	def payment
		set_reservation_item
		if @reservation_item
			@reservation_item.update(paymentStatus: true)
			respond_to do |format|
				format.html { redirect_to reservations_path, notice: 'Gracias por su Pago.' }
			end
		end
	end


	private

	def reservation_params
		reservation_params = params.require(:reservation).permit(:name)
	end

	def set_reservation_item
		@reservation_item = Reservation.find(params[:id])
	end
end

app/helpers/airline_helper.rb
module AirlineHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/flights/_flight.html.erb
<tr>
  <td><%= flight.airline.title %></td>
  <td><%= flight.origin %></td>
  <td><%= flight.destination %></td>
  <td><%= Time.at(flight.departure_time) %></td>
  <td><%= Time.at(flight.arrival_time) %></td>
  <td><%= number_to_currency(flight.price, :unit => "$") %></td>
  <td><%= link_to 'Agregar Vuelo', edit_flight_path(flight) if current_user %></td>
</tr>

app/views/flights/index.html.erb
<div class="row mb-3 justify-content-md-center">
    <div class="text-center">
      <h2>Vuelos</h2>
    </div>
  </div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Aerolinea</th>
      <th scope="col">Origen</th>
      <th scope="col">Destino</th>
      <th scope="col">Hora Llegada</th>
      <th scope="col">Hora Salida</th>
      <th scope="col">Precio</th>
      <th scope="col">Reservación</th>
    </tr>
  </thead>
  <tbody>
    <%= render @flights %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JAFFLY</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag 'logo.png' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-dark", style="background-color: #fd7e14;">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <a class="navbar-brand" href="#">
          <%= image_tag("logo.png", width: 80, height: 70) %>
        </a>

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Jaffly', root_path, :class => 'nav-link active' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Vuelos', flights_path, :class => 'nav-link active' %>
          </li>

          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Reservas', reservations_path, :class => 'nav-link active' %>
            </li>
          <% end %>

          <li class="nav-item">
            <a class="nav-link active" href="#">Sobre Nosotros</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" href="#">Contacto</a>
          </li>
        </ul>

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <% if user_signed_in? %>

              
            <li class="nav-item">
              <a class="nav-link active">Bienvenido,  <strong><%= current_user.name.upcase_first %></strong></a>
            </li>

            <li class="nav-item">
              <%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'nav-link active' %>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, method: :get, :class => 'nav-link active'  %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Crear Cuenta", new_user_registration_path, :class => 'nav-link active'  %>
            </li>
            <li class="nav-item">
              <%= link_to "Inicio Sesion", new_user_session_path, :class => 'nav-link active'  %>
            </li>
          <% end %>
        </ul>

      </div>
    </div>
  </nav>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_for @reservation_item do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<tr>
  <td><%= reservation.id %></td>
  <td><%= reservation.name %></td>
  <td><%= number_to_currency(reservation.value, :unit => "$") %></td>
  <td>
    <div class="row mb-3">
        <div class="col-2">
            <% if reservation.paymentStatus %>
                <button type="button" class="btn btn-success" disabled>Success</button>
            <% else %>
                <div class="col-2">
                    <%= link_to 'Pagar', payment_path(reservation), :class => 'btn btn-secondary active' %>
                </div>
            <% end %>
        </div>

        <div class="col-2">
            <%= link_to 'Mostrar Mas', reservation_path(reservation), :class => 'btn btn-secondary' %>
        </div>

        <div class="col-1">
            <%= link_to 'Editar', edit_reservation_path(reservation), :class => 'btn btn-warning active' %>
        </div>

        <div class="col-2">
            <%= link_to 'Escoger', change_path(reservation), :class => 'btn btn-warning active' %>
        </div>

        <div class="col-2">
            <%= button_to 'Eliminar', reservation_path(reservation), method: :delete, :class => 'btn btn-danger active' %>
        </div>
    </div>
  </td>
</tr>

app/views/reservations/edit.html.erb
<h1>Edit this Reservation item</h1>

<%= render 'form' %>

app/views/reservations/index.html.erb
<div class="row mb-2 justify-content-md-center">
    <div class="col-10">
        <div class="text-center">
          <h2>Reservas</h2>
        </div>
    </div>

    <div class="col-1">
        <%= link_to 'Crear Reserva', new_reservation_path, :class => 'btn btn-warning active' %>
    </div>
  </div>

<table class="table align-middle">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Precio</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody>
    <%= render @reservations %>
  </tbody>
</table>

app/views/reservations/new.html.erb
<h1>Create a new Reservation</h1>

<%= render 'form' %>

app/views/reservations/show.html.erb
<div class="row mb-3 justify-content-md-center">
    <div class="text-center">
        <h2>Titulo de Reserva: <%= @reservation_item.name %></h2>
    </div>
    <div class="text-center">
        <h3>Precio Total: <%= @reservation_item.value %></h2>
    </div>
    <!-- PAY BUTTON -->
</div>

<table class="table">
  <tr>
    <th scope="col">Aerolinea</th>
    <th scope="col">Origen</th>
    <th scope="col">Destino</th>
    <th scope="col">Hora Salida</th>
    <th scope="col">Hora Llegada</th>
    <th scope="col">Precio</th>
  </tr>

  <% @reservation_item.flights.each do |flight| %>
  <tr>
    <td><%= flight.airline.title %></td>
    <td><%= flight.origin %></td>
    <td><%= flight.destination %></td>
    <td><%= flight.departure_time %></td>
    <td><%= flight.arrival_time %></td>
    <td><%= flight.price %></td>
  </tr>
  <% end %>
</table>